{
 "title": "[UXP] Overview",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "UXP Transactions [UXP]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  toDate(timestamp) AS date,\n  count(*) AS Count\nFROM \"express_logger\".\"records\"\nWHERE timestamp >= now() - INTERVAL 30 DAY\nGROUP BY date\nORDER BY date\n"
    }
   ]
  },
  {
   "title": "all records per 5 sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(timestamp, INTERVAL 5 second) AS time,\n  count(*) AS total_count,\n  countIf(succeeded = true) AS succeeded_count,\n   countIf(succeeded = false) AS fail_count\nFROM express_logger.records\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "UXP Transaction Count [UXP]",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n    'Total' AS type,\n    count(*) AS count\nFROM \"express_logger\".\"records\"\nWHERE timestamp >= now() - INTERVAL 30 DAY\n\nUNION ALL\n\nSELECT\n    'Successful' AS type,\n    count(*) AS count\nFROM \"express_logger\".\"records\"\nWHERE timestamp >= now() - INTERVAL 30 DAY\n  AND succeeded = 1\n\nUNION ALL\n\nSELECT\n    'Failed' AS type,\n    count(*) AS count\nFROM \"express_logger\".\"records\"\nWHERE timestamp >= now() - INTERVAL 30 DAY\n  AND succeeded = 0"
    }
   ]
  },
  {
   "title": "failed records per 5 sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(timestamp, INTERVAL 5 second) AS time,\n  count(*) AS log_count\nFROM express_logger.records\nWHERE $__timeFilter(timestamp)\n  AND succeeded = false\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Popular Service Tags [UXP]",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n    serviceCode AS term,\n    count(*) AS Count\nFROM \"express_logger\".\"records\"\nWHERE timestamp >= now() - INTERVAL 30 DAY\nGROUP BY serviceCode\nORDER BY Count DESC\nLIMIT 100\n"
    }
   ]
  }
 ]
}